stages:
  - validate

include:
  - component: $CI_SERVER_FQDN/devops/ci-cd-components/php-quality@v1.8.0
    inputs:
      extra_system_packages: "libpng-dev libjpeg62-turbo-dev libfreetype6-dev"
      php_extensions: "zip gd"
      php_extension_configure_command: "docker-php-ext-configure gd --with-freetype --with-jpeg"
      lint_commands:
        - vendor/bin/phpcs --standard=PSR12 --extensions=php --warning-severity=0 src tests
      test_commands:
        - vendor/bin/phpunit --configuration ./phpunit.xml --testsuite Unit --no-coverage
        - vendor/bin/phpunit --configuration ./phpunit.xml --testsuite Integration --no-coverage
